### ISSUE TITLE
The components assembly module has to be "assembler agnostic"

### ISSUE THREAD

**Issue by loic-couderc** [bonsai-team/matam#24]
The components_assembly module has many references to SGA assembler.
This references have to be removed.

Moreover, add an option in matam_assembly to choose the assembler.

**Comment by loic-couderc** [comment]
By the way, add a parser for command line options.

**Comment by loic-couderc** [comment]
@ppericard : Is there a will to expose assembler parameters to matam_assembly.py as different assembler can have different parameters?

**Comment by ppericard** [comment]
@loic-couderc You're right, we should not expose the assembler parameters, but we could have some kind of parameter (or a switch) to change the assembler sensitivity. E.g. a "--sensitive" switch that would set up the assembler parameters to be more sensitive (and take more time/ressources in that case). Or a "--fast" switch with the contrary effect.
We also have to keep the "--read_correction" parameter in matam_assembly, since this could be independent of the chosen assembler.

**Comment by loic-couderc** [comment]
No "--sensitive" or "--fast" switch for the moment, but it should not be too hard to implement it if needed.
