### ISSUE TITLE
Problem completing installation (download-traindata)

### ISSUE THREAD

**Issue by ycl6** [bonsai-team/matam#36]
Installation halted after
```
download-traindata:
      [get] Getting: http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
      [get] To: /home/ycl6/tools/matam/RDPTools/classifier/build/classes/data.tgz
```
It seems data.tgz is unavailable, I even tried wget from the URL but failed. Is there an alternative location of the training data?

**Comment by ppericard** [comment]
Hi,
could you try again getting the RDP training data from the same URL. The url works ok from our university (Lille1 in France).
If it doesnt, maybe try using some sort of vpn or proxy to get it because your IP adress might be blacklisted.
Keep us in the loop so if none of these solution works we'll contact the RDP team to find out if they have a mirror site from where you can download this data.

**Comment by ppericard** [comment]
If you want to use MATAM, you can also get it from conda, which is the easier way to get it.
Just follow the instructions from our README on the main repository page.

**Comment by ycl6** [comment]
Hi @ppericard it seems the server hosting the training data was unstable at some times, I used `wget -c` to let the command retry downloading the files and was successful in the end.

What's your recommendation for analysing paired-end reads? From the reading of the open issues, MATAM doesn't handle PE reads right now. Do I concatenate R1 and R2 to generate a single file as input? Can I used a gzipped fastq file as input?

**Comment by ppericard** [comment]
Hi @ycl6, glad to read that you dealt with that problem.
To analyze paired-end reads you can indeed put together all your reads in the same file and pass that file to MATAM. However, we do not support gzipped fastq files as of now, but it could be done in the future since SortMeRNA (our first step) does support them. Thank for the suggestion, I opened a new issue (#37)
